openapi: 3.0.0
info:
  version: "1.0"
  title: DBoM Agent
  description: The HTTP REST API for the Distributed Bill of Materials Agent
  contact:
    name: Ryan
    email: Ryan.Mathison2@unisys.com
paths:
  /channels:
    parameters: []
    get:
      summary: List Channels
      tags:
        - Record
      operationId: ListRecords
      deprecated: false
      responses:
        "200":
          description: Array of channel ids retrieved successfully
        "404":
          description: No channels found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
        "500":
          description: Error on agent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
        "502":
          description: Error in repository
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
  "/channels/{channelID}/records":
    parameters:
      - name: channelID
        in: path
        required: true
        description: Channel ID
        schema:
          type: string
    get:
      summary: List Records
      tags:
        - Record
      operationId: ListRecordsPost
      deprecated: false
      responses:
        "200":
          description: Array of record ids retrieved successfully
        "404":
          description: No records found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
        "500":
          description: Error on agent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
        "502":
          description: Error in repository
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
    post:
      summary: Commit a Record
      tags:
        - Record
      parameters:
        - name: commit-type
          in: header
          required: true
          description: Commit Type
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RecordDefinition"
        required: true
      operationId: CommitRecord
      deprecated: false
      responses:
        "200":
          description: Record has been created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateRecordResponseDefinition"
        "404":
          description: Channel does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
        "409":
          description: Record already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
        "500":
          description: Error on agent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
        "502":
          description: Error in repository
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
  "/channels/{channelID}/records/_query":
    parameters:
      - name: channelID
        in: path
        required: true
        description: Channel ID
        schema:
          type: string
    get:
      summary: Query Records
      tags:
        - Record
      parameters:
        - name: query
          in: query
          required: true
          description: Query
          schema:
            type: string
        - name: fields
          in: query
          required: false
          description: Fields to return
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: Pagination limit
          schema:
            type: integer
        - name: skip
          in: query
          required: false
          description: Pagination skip
          schema:
            type: integer
      operationId: QueryRecords
      deprecated: false
      responses:
        "200":
          description: Records have been retrieved successfully
        "404":
          description: Channel does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
        "500":
          description: Error on agent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
        "502":
          description: Error in repository
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
    post:
      summary: Query Records
      tags:
        - Record
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QueryRecordDefinition"
        required: true
      operationId: QueryRecordsPost
      deprecated: false
      responses:
        "200":
          description: Records have been retrieved successfully
        "404":
          description: Channel does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
        "500":
          description: Error on agent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
        "502":
          description: Error in repository
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
  "/channels/{channelID}/records/{recordID}":
    parameters:
      - name: recordID
        in: path
        required: true
        description: Record ID
        schema:
          type: string
      - name: channelID
        in: path
        required: true
        description: Channel ID
        schema:
          type: string
    get:
      summary: Query a Record
      tags:
        - Record
      operationId: RetrieveRecord
      deprecated: false
      responses:
        "200":
          description: Record has been retrieved and is in the body
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExampleRecordPayloadDefinition"
        "404":
          description: Channel and/or record does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
        "500":
          description: Error on agent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
        "502":
          description: Error in repository
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
  "/channels/{channelID}/records/{recordID}/audit":
    parameters:
      - name: recordID
        in: path
        required: true
        description: Record ID
        schema:
          type: string
      - name: channelID
        in: path
        required: true
        description: Channel ID
        schema:
          type: string
    get:
      summary: Audit an record
      tags:
        - Record
      operationId: AuditRecord
      deprecated: false
      responses:
        "200":
          description: Record Audit Trail has been retrieved and is in the body
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuditResponseDefinition"
        "404":
          description: Channel and/or record does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
        "500":
          description: Error on agent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
        "502":
          description: Error in repository
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDefinition"
tags:
  - name: Record
    description: ""
servers:
  - url: http://localhost:3000/
components:
  schemas:
    RecordDefinition:
      title: RecordDefinition
      example:
        recordID: exampleRecord
        recordIDPayload:
          example: example
      type: object
      properties:
        recordID:
          type: string
        recordIDPayload:
          type: object
      required:
        - recordID
        - recordIDPayload
    QueryRecordDefinition:
      title: QueryRecordDefinition
      example:
        query:
          $and:
            - assetType:
                $eq: HardwareComponent
            - assetSubType:
                $eq: CPUUnit
        fields:
          - documentCreator
          - documentCreatedDate
          - documentName
          - assetManufacturer
          - assetMetadata
          - manufactureSignature
        limit: 20
        skip: 0
      type: object
      properties:
        query:
          type: object
        fields:
          type: array
          items:
            type: string
        limit:
          type: integer
        skip:
          type: integer
      required:
        - query
    CreateRecordResponseDefinition:
      title: CreateRecordResponseDefinition
      example:
        success: true
      type: object
      properties:
        success:
          type: boolean
      required:
        - success
    ErrorResponseDefinition:
      title: ErrorResponseDefinition
      example:
        success: false
        status: No resource found
        error: Channel query failed
      type: object
      properties:
        success:
          type: boolean
        status:
          type: string
        error:
          type: string
      required:
        - success
        - status
    ExampleRecordPayloadDefinition:
      title: ExampleRecordPayloadDefinition
      example:
        example: example
    AuditResponseDefinition:
      title: AuditResponseDefinition
      example:
        history:
          - _id: 3412
            timestamp: 2020-9-01T21:04:14.840Z
            payload:
              example: example
            resourceID: exampleRecord
            eventType: CREATE
            channelID: exampleChannel
          - _id: 3474
            timestamp: 2020-10-02T11:54:35.345Z
            payload:
              example: exampleUpdated
            resourceID: exampleRecord
            eventType: UPDATE
            channelID: exampleChannel
      type: object
      properties:
        history:
          type: array
          items:
            $ref: "#/components/schemas/AuditDefinition"
      required:
        - history
    AuditDefinition:
      title: AuditDefinition
      example:
        _id: 3412
        timestamp: 2020-10-01T21:04:14.840Z
        payload:
          example: example
        resourceID: exampleRecord
        eventType: CREATE
        channelID: exampleChannel
      type: object
      properties:
        _id:
          type: integer
          format: int64
        timestamp:
          type: string
          format: date-time
        payload:
          type: object
        resourceID:
          type: string
        eventType:
          type: string
        channelID:
          type: string
      required:
        - _id
        - timestamp
        - payload
        - resourceID
        - eventType
        - channelID
