openapi: 3.0.0
info:
  version: "1.0"
  title: PGP Service
  description: HTTP REST API for signing and verifying data with pgp keys
  contact:
    name: Ryan
    email: ryan.mathison2@unisys.com
paths:
  /pgp/sign:
    post:
      summary: Sign data  with PGP key
      operationId: SignData
      deprecated: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignDataDefinition"
        required: true
      responses:
        "200":
          description: Data successfully signed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignResponseDefinition"
        "400":
          description: Failed to sign data
  /pgp/validate:
    post:
      summary: Validate data signed by a PGP key
      operationId: ValdiateData
      deprecated: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ValidateDataDefinition"
        required: true
      responses:
        "200":
          description: Data validation complete
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidateResponseDefinition"
        "400":
          description: Failed to validate data
servers:
  - url: http://localhost:5000/
components:
  schemas:
    SignDataDefinition:
      title: SignDataDefinition
      example:
        exampleString: ""
        exampleNumber: 1
        exampleObject:
          exampleNumber: 1
          exampleString: ""
      type: object
      properties:
        exampleString:
          type: string
        exampleNumber:
          type: number
        exampleObject:
          type: object
    ValidateDataDefinition:
      title: ValidateDataDefinition
      example:
        signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0NClZlcnNpb246IE9wZW5QR1AuanMgdjQuMTAuNA0KQ29tbWVudDogaHR0cHM6Ly9vcGVucGdwanMub3JnDQoNCndsNEVBUk1JQUFZRkFsOWhLcTBBQ2drUUQvazhJWktxZXU4UDd3RCtJb2NidlVtNEowOU41WDVQREtxVA0Kc3hFYkZLeWJEd2g0WE93MnF6L0QycDhCQUozZkxVQmF1Uk1VcWJjbk1kQzRJOW5GUWF1V05XQXRmempBDQpOUUwwa0Nxcw0KPXBtZmcNCi0tLS0tRU5EIFBHUCBTSUdOQVRVUkUtLS0tLQ0K
        fingerprint: a2cfe3db6dcf3ad0b5284a6d0ff93c2192aa7aef
        input:
          exampleString: ""
          exampleNumber: 1
          exampleObject:
            exampleNumber: 1
            exampleString: ""
      type: object
      properties:
        signature:
          type: string
        fingerprint:
          type: string
        input:
          type: object
      required:
        - signature
        - fingerprint
        - input
    SignResponseDefinition:
      title: ValidateResponseDefinition
      example:
        signature: LS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0NClZlcnNpb246IE9wZW5QR1AuanMgdjQuMTAuNA0KQ29tbWVudDogaHR0cHM6Ly9vcGVucGdwanMub3JnDQoNCndsNEVBUk1JQUFZRkFsOW8vSDBBQ2drUUQvazhJWktxZXU5Vm13RUEzTzlOSWM2MXpuaGFVc2JyekIzRw0KR2o1eFZCVHBmQy9LcmRJZTlMNWVvazBBLzAzVEdBQkdDNUJ2MTFkY3dRVnVoZlVFUkhOd2ozSUQvdytzDQpnUXRyTVJXWQ0KPWVkdEQNCi0tLS0tRU5EIFBHUCBTSUdOQVRVUkUtLS0tLQ0K
        fingerprint: a2cfe3db6dcf3ad0b5284a6d0ff93c2192aa7aef
      type: object
      properties:
        signature:
          type: string
        fingerprint:
          type: string
      required:
        - signature
        - fingerprint
    ValidateResponseDefinition:
      title: ValidateResponseDefinition
      example:
        valid: true
        success: true
      type: object
      properties:
        valid:
          type: boolean
        success:
          type: boolean
      required:
        - valid
        - success